//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Secrets struct {
	ID        int64 `sql:"primary_key"`
	UserID    int64
	TypeID    int64
	Name      string
	Content   []byte
	CreatedAt time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
