// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: secret/private/api.proto

package private

import (
	secret "github.com/evgenivanovi/gophkeeper/api/pb/secret"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDecodedSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *CreateDecodedSecretRequest_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreateDecodedSecretRequest) Reset() {
	*x = CreateDecodedSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDecodedSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecodedSecretRequest) ProtoMessage() {}

func (x *CreateDecodedSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecodedSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateDecodedSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDecodedSecretRequest) GetPayload() *CreateDecodedSecretRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateDecodedSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *CreateDecodedSecretResponse_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreateDecodedSecretResponse) Reset() {
	*x = CreateDecodedSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDecodedSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecodedSecretResponse) ProtoMessage() {}

func (x *CreateDecodedSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecodedSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateDecodedSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDecodedSecretResponse) GetPayload() *CreateDecodedSecretResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateEncodedSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *CreateEncodedSecretRequest_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreateEncodedSecretRequest) Reset() {
	*x = CreateEncodedSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncodedSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncodedSecretRequest) ProtoMessage() {}

func (x *CreateEncodedSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncodedSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateEncodedSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEncodedSecretRequest) GetPayload() *CreateEncodedSecretRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateEncodedSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *CreateEncodedSecretResponse_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreateEncodedSecretResponse) Reset() {
	*x = CreateEncodedSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncodedSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncodedSecretResponse) ProtoMessage() {}

func (x *CreateEncodedSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncodedSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateEncodedSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEncodedSecretResponse) GetPayload() *CreateEncodedSecretResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateDecodedSecretRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *secret.DecodedSecretData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId int64                     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateDecodedSecretRequest_Payload) Reset() {
	*x = CreateDecodedSecretRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDecodedSecretRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecodedSecretRequest_Payload) ProtoMessage() {}

func (x *CreateDecodedSecretRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecodedSecretRequest_Payload.ProtoReflect.Descriptor instead.
func (*CreateDecodedSecretRequest_Payload) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateDecodedSecretRequest_Payload) GetData() *secret.DecodedSecretData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDecodedSecretRequest_Payload) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateDecodedSecretResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *secret.EncodedSecret `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateDecodedSecretResponse_Payload) Reset() {
	*x = CreateDecodedSecretResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDecodedSecretResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecodedSecretResponse_Payload) ProtoMessage() {}

func (x *CreateDecodedSecretResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecodedSecretResponse_Payload.ProtoReflect.Descriptor instead.
func (*CreateDecodedSecretResponse_Payload) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateDecodedSecretResponse_Payload) GetData() *secret.EncodedSecret {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateEncodedSecretRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *secret.EncodedSecretData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId int64                     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateEncodedSecretRequest_Payload) Reset() {
	*x = CreateEncodedSecretRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncodedSecretRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncodedSecretRequest_Payload) ProtoMessage() {}

func (x *CreateEncodedSecretRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncodedSecretRequest_Payload.ProtoReflect.Descriptor instead.
func (*CreateEncodedSecretRequest_Payload) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateEncodedSecretRequest_Payload) GetData() *secret.EncodedSecretData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateEncodedSecretRequest_Payload) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateEncodedSecretResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *secret.EncodedSecret `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateEncodedSecretResponse_Payload) Reset() {
	*x = CreateEncodedSecretResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_private_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncodedSecretResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncodedSecretResponse_Payload) ProtoMessage() {}

func (x *CreateEncodedSecretResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_secret_private_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncodedSecretResponse_Payload.ProtoReflect.Descriptor instead.
func (*CreateEncodedSecretResponse_Payload) Descriptor() ([]byte, []int) {
	return file_secret_private_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateEncodedSecretResponse_Payload) GetData() *secret.EncodedSecret {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_secret_private_api_proto protoreflect.FileDescriptor

var file_secret_private_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x1a, 0x12, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd,
	0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x51, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa2,
	0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x34, 0x0a,
	0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e,
	0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xbd, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4c, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x1a, 0x51, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x1a, 0x34, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x29, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xf1, 0x01, 0x0a, 0x1b, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x50, 0x49, 0x12, 0x68, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x76, 0x67, 0x65, 0x6e,
	0x69, 0x76, 0x61, 0x6e, 0x6f, 0x76, 0x69, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secret_private_api_proto_rawDescOnce sync.Once
	file_secret_private_api_proto_rawDescData = file_secret_private_api_proto_rawDesc
)

func file_secret_private_api_proto_rawDescGZIP() []byte {
	file_secret_private_api_proto_rawDescOnce.Do(func() {
		file_secret_private_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_secret_private_api_proto_rawDescData)
	})
	return file_secret_private_api_proto_rawDescData
}

var file_secret_private_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_secret_private_api_proto_goTypes = []interface{}{
	(*CreateDecodedSecretRequest)(nil),          // 0: secret_private.CreateDecodedSecretRequest
	(*CreateDecodedSecretResponse)(nil),         // 1: secret_private.CreateDecodedSecretResponse
	(*CreateEncodedSecretRequest)(nil),          // 2: secret_private.CreateEncodedSecretRequest
	(*CreateEncodedSecretResponse)(nil),         // 3: secret_private.CreateEncodedSecretResponse
	(*CreateDecodedSecretRequest_Payload)(nil),  // 4: secret_private.CreateDecodedSecretRequest.Payload
	(*CreateDecodedSecretResponse_Payload)(nil), // 5: secret_private.CreateDecodedSecretResponse.Payload
	(*CreateEncodedSecretRequest_Payload)(nil),  // 6: secret_private.CreateEncodedSecretRequest.Payload
	(*CreateEncodedSecretResponse_Payload)(nil), // 7: secret_private.CreateEncodedSecretResponse.Payload
	(*secret.DecodedSecretData)(nil),            // 8: secret.DecodedSecretData
	(*secret.EncodedSecret)(nil),                // 9: secret.EncodedSecret
	(*secret.EncodedSecretData)(nil),            // 10: secret.EncodedSecretData
}
var file_secret_private_api_proto_depIdxs = []int32{
	4,  // 0: secret_private.CreateDecodedSecretRequest.payload:type_name -> secret_private.CreateDecodedSecretRequest.Payload
	5,  // 1: secret_private.CreateDecodedSecretResponse.payload:type_name -> secret_private.CreateDecodedSecretResponse.Payload
	6,  // 2: secret_private.CreateEncodedSecretRequest.payload:type_name -> secret_private.CreateEncodedSecretRequest.Payload
	7,  // 3: secret_private.CreateEncodedSecretResponse.payload:type_name -> secret_private.CreateEncodedSecretResponse.Payload
	8,  // 4: secret_private.CreateDecodedSecretRequest.Payload.data:type_name -> secret.DecodedSecretData
	9,  // 5: secret_private.CreateDecodedSecretResponse.Payload.data:type_name -> secret.EncodedSecret
	10, // 6: secret_private.CreateEncodedSecretRequest.Payload.data:type_name -> secret.EncodedSecretData
	9,  // 7: secret_private.CreateEncodedSecretResponse.Payload.data:type_name -> secret.EncodedSecret
	0,  // 8: secret_private.InternalSecretManagementAPI.CreateDecoded:input_type -> secret_private.CreateDecodedSecretRequest
	2,  // 9: secret_private.InternalSecretManagementAPI.CreateEncoded:input_type -> secret_private.CreateEncodedSecretRequest
	1,  // 10: secret_private.InternalSecretManagementAPI.CreateDecoded:output_type -> secret_private.CreateDecodedSecretResponse
	3,  // 11: secret_private.InternalSecretManagementAPI.CreateEncoded:output_type -> secret_private.CreateEncodedSecretResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_secret_private_api_proto_init() }
func file_secret_private_api_proto_init() {
	if File_secret_private_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secret_private_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDecodedSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDecodedSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncodedSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncodedSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDecodedSecretRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDecodedSecretResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncodedSecretRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_private_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncodedSecretResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secret_private_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_private_api_proto_goTypes,
		DependencyIndexes: file_secret_private_api_proto_depIdxs,
		MessageInfos:      file_secret_private_api_proto_msgTypes,
	}.Build()
	File_secret_private_api_proto = out.File
	file_secret_private_api_proto_rawDesc = nil
	file_secret_private_api_proto_goTypes = nil
	file_secret_private_api_proto_depIdxs = nil
}
