// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: secret/private/api.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InternalSecretManagementAPI_CreateDecoded_FullMethodName = "/secret_private.InternalSecretManagementAPI/CreateDecoded"
	InternalSecretManagementAPI_CreateEncoded_FullMethodName = "/secret_private.InternalSecretManagementAPI/CreateEncoded"
)

// InternalSecretManagementAPIClient is the client API for InternalSecretManagementAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalSecretManagementAPIClient interface {
	CreateDecoded(ctx context.Context, in *CreateDecodedSecretRequest, opts ...grpc.CallOption) (*CreateDecodedSecretResponse, error)
	CreateEncoded(ctx context.Context, in *CreateEncodedSecretRequest, opts ...grpc.CallOption) (*CreateEncodedSecretResponse, error)
}

type internalSecretManagementAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalSecretManagementAPIClient(cc grpc.ClientConnInterface) InternalSecretManagementAPIClient {
	return &internalSecretManagementAPIClient{cc}
}

func (c *internalSecretManagementAPIClient) CreateDecoded(ctx context.Context, in *CreateDecodedSecretRequest, opts ...grpc.CallOption) (*CreateDecodedSecretResponse, error) {
	out := new(CreateDecodedSecretResponse)
	err := c.cc.Invoke(ctx, InternalSecretManagementAPI_CreateDecoded_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalSecretManagementAPIClient) CreateEncoded(ctx context.Context, in *CreateEncodedSecretRequest, opts ...grpc.CallOption) (*CreateEncodedSecretResponse, error) {
	out := new(CreateEncodedSecretResponse)
	err := c.cc.Invoke(ctx, InternalSecretManagementAPI_CreateEncoded_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalSecretManagementAPIServer is the server API for InternalSecretManagementAPI service.
// All implementations must embed UnimplementedInternalSecretManagementAPIServer
// for forward compatibility
type InternalSecretManagementAPIServer interface {
	CreateDecoded(context.Context, *CreateDecodedSecretRequest) (*CreateDecodedSecretResponse, error)
	CreateEncoded(context.Context, *CreateEncodedSecretRequest) (*CreateEncodedSecretResponse, error)
	mustEmbedUnimplementedInternalSecretManagementAPIServer()
}

// UnimplementedInternalSecretManagementAPIServer must be embedded to have forward compatible implementations.
type UnimplementedInternalSecretManagementAPIServer struct {
}

func (UnimplementedInternalSecretManagementAPIServer) CreateDecoded(context.Context, *CreateDecodedSecretRequest) (*CreateDecodedSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDecoded not implemented")
}
func (UnimplementedInternalSecretManagementAPIServer) CreateEncoded(context.Context, *CreateEncodedSecretRequest) (*CreateEncodedSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEncoded not implemented")
}
func (UnimplementedInternalSecretManagementAPIServer) mustEmbedUnimplementedInternalSecretManagementAPIServer() {
}

// UnsafeInternalSecretManagementAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalSecretManagementAPIServer will
// result in compilation errors.
type UnsafeInternalSecretManagementAPIServer interface {
	mustEmbedUnimplementedInternalSecretManagementAPIServer()
}

func RegisterInternalSecretManagementAPIServer(s grpc.ServiceRegistrar, srv InternalSecretManagementAPIServer) {
	s.RegisterService(&InternalSecretManagementAPI_ServiceDesc, srv)
}

func _InternalSecretManagementAPI_CreateDecoded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDecodedSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalSecretManagementAPIServer).CreateDecoded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalSecretManagementAPI_CreateDecoded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalSecretManagementAPIServer).CreateDecoded(ctx, req.(*CreateDecodedSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalSecretManagementAPI_CreateEncoded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEncodedSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalSecretManagementAPIServer).CreateEncoded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalSecretManagementAPI_CreateEncoded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalSecretManagementAPIServer).CreateEncoded(ctx, req.(*CreateEncodedSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalSecretManagementAPI_ServiceDesc is the grpc.ServiceDesc for InternalSecretManagementAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalSecretManagementAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secret_private.InternalSecretManagementAPI",
	HandlerType: (*InternalSecretManagementAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDecoded",
			Handler:    _InternalSecretManagementAPI_CreateDecoded_Handler,
		},
		{
			MethodName: "CreateEncoded",
			Handler:    _InternalSecretManagementAPI_CreateEncoded_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret/private/api.proto",
}
