// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: secret/model.proto

package secret

import (
	common "github.com/evgenivanovi/gophkeeper/api/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodedSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data     *DecodedSecretData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata *common.Metadata   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *DecodedSecret) Reset() {
	*x = DecodedSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedSecret) ProtoMessage() {}

func (x *DecodedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedSecret.ProtoReflect.Descriptor instead.
func (*DecodedSecret) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{0}
}

func (x *DecodedSecret) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecodedSecret) GetData() *DecodedSecretData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecodedSecret) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EncodedSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data     *EncodedSecretData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata *common.Metadata   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *EncodedSecret) Reset() {
	*x = EncodedSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedSecret) ProtoMessage() {}

func (x *EncodedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedSecret.ProtoReflect.Descriptor instead.
func (*EncodedSecret) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedSecret) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EncodedSecret) GetData() *EncodedSecretData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodedSecret) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DecodedSecretData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    string         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content *SecretContent `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *DecodedSecretData) Reset() {
	*x = DecodedSecretData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodedSecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedSecretData) ProtoMessage() {}

func (x *DecodedSecretData) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedSecretData.ProtoReflect.Descriptor instead.
func (*DecodedSecretData) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{2}
}

func (x *DecodedSecretData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecodedSecretData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DecodedSecretData) GetContent() *SecretContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type EncodedSecretData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *EncodedSecretData) Reset() {
	*x = EncodedSecretData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedSecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedSecretData) ProtoMessage() {}

func (x *EncodedSecretData) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedSecretData.ProtoReflect.Descriptor instead.
func (*EncodedSecretData) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{3}
}

func (x *EncodedSecretData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncodedSecretData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EncodedSecretData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SecretContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*SecretContent_Text
	//	*SecretContent_Binary
	//	*SecretContent_Credentials
	//	*SecretContent_Card
	Kind isSecretContent_Kind `protobuf_oneof:"kind"`
}

func (x *SecretContent) Reset() {
	*x = SecretContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretContent) ProtoMessage() {}

func (x *SecretContent) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretContent.ProtoReflect.Descriptor instead.
func (*SecretContent) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{4}
}

func (m *SecretContent) GetKind() isSecretContent_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *SecretContent) GetText() *TextSecretContent {
	if x, ok := x.GetKind().(*SecretContent_Text); ok {
		return x.Text
	}
	return nil
}

func (x *SecretContent) GetBinary() *BinarySecretContent {
	if x, ok := x.GetKind().(*SecretContent_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *SecretContent) GetCredentials() *CredentialsSecretContent {
	if x, ok := x.GetKind().(*SecretContent_Credentials); ok {
		return x.Credentials
	}
	return nil
}

func (x *SecretContent) GetCard() *CardSecretContent {
	if x, ok := x.GetKind().(*SecretContent_Card); ok {
		return x.Card
	}
	return nil
}

type isSecretContent_Kind interface {
	isSecretContent_Kind()
}

type SecretContent_Text struct {
	Text *TextSecretContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type SecretContent_Binary struct {
	Binary *BinarySecretContent `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

type SecretContent_Credentials struct {
	Credentials *CredentialsSecretContent `protobuf:"bytes,3,opt,name=credentials,proto3,oneof"`
}

type SecretContent_Card struct {
	Card *CardSecretContent `protobuf:"bytes,4,opt,name=card,proto3,oneof"`
}

func (*SecretContent_Text) isSecretContent_Kind() {}

func (*SecretContent_Binary) isSecretContent_Kind() {}

func (*SecretContent_Credentials) isSecretContent_Kind() {}

func (*SecretContent_Card) isSecretContent_Kind() {}

type TextSecretContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextSecretContent) Reset() {
	*x = TextSecretContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextSecretContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSecretContent) ProtoMessage() {}

func (x *TextSecretContent) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSecretContent.ProtoReflect.Descriptor instead.
func (*TextSecretContent) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{5}
}

func (x *TextSecretContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BinarySecretContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *BinarySecretContent) Reset() {
	*x = BinarySecretContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinarySecretContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinarySecretContent) ProtoMessage() {}

func (x *BinarySecretContent) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinarySecretContent.ProtoReflect.Descriptor instead.
func (*BinarySecretContent) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{6}
}

func (x *BinarySecretContent) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type CredentialsSecretContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CredentialsSecretContent) Reset() {
	*x = CredentialsSecretContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialsSecretContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsSecretContent) ProtoMessage() {}

func (x *CredentialsSecretContent) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsSecretContent.ProtoReflect.Descriptor instead.
func (*CredentialsSecretContent) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialsSecretContent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsSecretContent) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CardSecretContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
	Cvv string `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Due string `protobuf:"bytes,3,opt,name=due,proto3" json:"due,omitempty"`
}

func (x *CardSecretContent) Reset() {
	*x = CardSecretContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secret_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardSecretContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardSecretContent) ProtoMessage() {}

func (x *CardSecretContent) ProtoReflect() protoreflect.Message {
	mi := &file_secret_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardSecretContent.ProtoReflect.Descriptor instead.
func (*CardSecretContent) Descriptor() ([]byte, []int) {
	return file_secret_model_proto_rawDescGZIP(), []int{8}
}

func (x *CardSecretContent) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *CardSecretContent) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardSecretContent) GetDue() string {
	if x != nil {
		return x.Due
	}
	return ""
}

var File_secret_model_proto protoreflect.FileDescriptor

var file_secret_model_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x15, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x7c, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x6c, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x11, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0xf6, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x44,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x27, 0x0a,
	0x11, 0x54, 0x65, 0x78, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2b, 0x0a, 0x13, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x76, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x76, 0x76,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x75, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x76, 0x67, 0x65, 0x6e, 0x69, 0x76, 0x61, 0x6e, 0x6f, 0x76, 0x69, 0x2f, 0x67, 0x6f,
	0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secret_model_proto_rawDescOnce sync.Once
	file_secret_model_proto_rawDescData = file_secret_model_proto_rawDesc
)

func file_secret_model_proto_rawDescGZIP() []byte {
	file_secret_model_proto_rawDescOnce.Do(func() {
		file_secret_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_secret_model_proto_rawDescData)
	})
	return file_secret_model_proto_rawDescData
}

var file_secret_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_secret_model_proto_goTypes = []interface{}{
	(*DecodedSecret)(nil),            // 0: secret.DecodedSecret
	(*EncodedSecret)(nil),            // 1: secret.EncodedSecret
	(*DecodedSecretData)(nil),        // 2: secret.DecodedSecretData
	(*EncodedSecretData)(nil),        // 3: secret.EncodedSecretData
	(*SecretContent)(nil),            // 4: secret.SecretContent
	(*TextSecretContent)(nil),        // 5: secret.TextSecretContent
	(*BinarySecretContent)(nil),      // 6: secret.BinarySecretContent
	(*CredentialsSecretContent)(nil), // 7: secret.CredentialsSecretContent
	(*CardSecretContent)(nil),        // 8: secret.CardSecretContent
	(*common.Metadata)(nil),          // 9: common.Metadata
}
var file_secret_model_proto_depIdxs = []int32{
	2, // 0: secret.DecodedSecret.data:type_name -> secret.DecodedSecretData
	9, // 1: secret.DecodedSecret.metadata:type_name -> common.Metadata
	3, // 2: secret.EncodedSecret.data:type_name -> secret.EncodedSecretData
	9, // 3: secret.EncodedSecret.metadata:type_name -> common.Metadata
	4, // 4: secret.DecodedSecretData.content:type_name -> secret.SecretContent
	5, // 5: secret.SecretContent.text:type_name -> secret.TextSecretContent
	6, // 6: secret.SecretContent.binary:type_name -> secret.BinarySecretContent
	7, // 7: secret.SecretContent.credentials:type_name -> secret.CredentialsSecretContent
	8, // 8: secret.SecretContent.card:type_name -> secret.CardSecretContent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_secret_model_proto_init() }
func file_secret_model_proto_init() {
	if File_secret_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secret_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodedSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodedSecretData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedSecretData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextSecretContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinarySecretContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialsSecretContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secret_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardSecretContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_secret_model_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*SecretContent_Text)(nil),
		(*SecretContent_Binary)(nil),
		(*SecretContent_Credentials)(nil),
		(*SecretContent_Card)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secret_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secret_model_proto_goTypes,
		DependencyIndexes: file_secret_model_proto_depIdxs,
		MessageInfos:      file_secret_model_proto_msgTypes,
	}.Build()
	File_secret_model_proto = out.File
	file_secret_model_proto_rawDesc = nil
	file_secret_model_proto_goTypes = nil
	file_secret_model_proto_depIdxs = nil
}
